name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VPS_IP: "188.245.216.187"

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H $VPS_IP  >> ~/.ssh/known_hosts
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy
        run: |
          cat << 'SCRIPT' > deploy_script.sh
          #!/bin/bash
          sudo apt install unzip -y
          export ADMIN_PASSWD="${{ vars.ADMIN_PASSWD }}"
          export PROJECT_DIR="${{ vars.PROJECT_DIR }}"
          export GITHUB_REPOSITORY="${{ github.repository }}"
          export SMTP_PASSWORD="${{vars.SMTP_PASSWORD}}"
          export SMTP_USER_NAME="${{vars.SMTP_USER_NAME}}"
          export MAIL_SMTP_FROM="${{vars.MAIL_SMTP_FROM}}"
          export OPEN_ID_CLIENT_SECRET="${{vars.OPEN_ID_CLIENT_SECRET}}"
          export AUTH_DOMAIN="${{vars.AUTH_DOMAIN}}"

          set -e  # Exit on errors
          echo "PROJECT_DIR=$PROJECT_DIR"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "ADMIN_PASSWD=$ADMIN_PASSWD"
          echo "SMTP_PASSWORD=$SMTP_PASSWORD"
          # Check if the directory exists
          if [ ! -d "$PROJECT_DIR" ]; then
            echo "Directory does not exist. Cloning the repository..."
            mkdir -p "$PROJECT_DIR"
            git clone "https://github.com/$GITHUB_REPOSITORY".git "$PROJECT_DIR"
          fi

          echo "Navigate to the project directory"
          cd "$PROJECT_DIR"

          echo "Ensure the repository is clean"
          git reset --hard
          git clean -fd
          git fetch origin main
          git reset --hard origin/main

          curl -L https://github.com/OCA/server-auth/archive/refs/heads/14.0.zip -o auth_oauth_autologin.zip
          curl -L https://github.com/jcardus/odoo-traccar/archive/refs/heads/master.zip -o odoo-traccar.zip
          echo "Extracting the module"
          unzip auth_oauth_autologin.zip
          unzip odoo-traccar.zip          
          mv -v odoo-traccar-master frotaweb
          mv -v server-auth-14.0/auth_oauth_autologin frotaweb addons
          rm -rf server-auth-14.0 auth_oauth_autologin.zip odoo-traccar.zip || true
          echo "running sed"
          sed -i "s/%%admin_passwd%%/$ADMIN_PASSWD/g" odoo/odoo.conf    
          sed -i "s|%%SMTP_PASSWORD%%|$SMTP_PASSWORD|g" odoo/odoo.conf  
          sed -i "s/%%SMTP_USER_NAME%%/$SMTP_USER_NAME/g" odoo/odoo.conf  
          sed -i "s/%%MAIL_SMTP_FROM%%/$MAIL_SMTP_FROM/g" odoo/odoo.conf
          sed -i "s|%%AUTH_DOMAIN%%|$AUTH_DOMAIN|g" addons/frotaweb/data/oauth_provider_data.xml
          sed -i "s|%%OPEN_ID_CLIENT_SECRET%%|$OPEN_ID_CLIENT_SECRET|g" 18.0/odoo/addons/auth_oauth/models/res_users.py
          echo "copy files"
          docker cp ./18.0 odoo:/usr/lib/python3/dist-packages      
          echo "restart"
          docker-compose down
          docker-compose up -d
          docker cp ./18.0/odoo odoo:/usr/lib/python3/dist-packages
          SCRIPT
          chmod +x deploy_script.sh
          
          ssh root@$VPS_IP 'bash -s' < deploy_script.sh
